CREATE TABLE unity_expenses (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    vendor TEXT NOT NULL,
    note TEXT,
    price INTEGER NOT NULL,
    event_id INTEGER REFERENCES unity_weddings(id) NOT NULL
);